title: "Zhenyuan Lu, PhD | Personal Page"
description: "I am a deep learning scientist at Seurat and an adjunct faculty member teaching AI/ML at Northeastern University. I received my PhD from Northeastern, with research interests in representation learning and self-supervised learning."
baseurl: "" # Leave empty if deploying to username.github.io
url: "https://zhenyuanlu.com" # Your custom domain or https://username.github.io

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

icon_set: "lucide"  # options: lucide or fontawesome

google_analytics_id: G-YKJ7CXRCW1 

author:
  name: "Zhenyuan Lu"
  email: "lu.zhenyua@northeastern.edu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-email-protect
  - kramdown
  
include:
  - _pages
  - _blog
  - section/blog_card.html

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - thumb_gen
  - "*.js"
  - "*.json"
  - "*.scss"
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json

collections:
  blog:
    output: true
    permalink: /:collection/:slug/

sass:
  style: compressed
  sass_dir: _sass

# KaTeX Configuration
katex:
  js_path: "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"
  css_path: "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"
  auto_render_path: "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"
  rendering_options:
    throw_error: true
    error_color: "#cc0000"