# Site settings
author: Zhenyuan Lu
name: Zhenyuan Lu
title: Zhenyuan Lu
email: lu.zhenyua@northeastern.edu
description: >
  Machine learning and PhD research fellow at Northeastern University.
  Using background and experience working in Biomedical sciences
  and data science fields over the last 10 years.
  I weave healthcare and machine learning concepts together.

url: "https://zhenyuanlu.com/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

github_username: zhenyuanlu
google_analytics: G-YKJ7CXRCW1
youtube_channel:
rss:  # notes rss

permalink: /:categories/:title/


show_social_icons:  true
enable_anchorjs:    true
enable_latexjs:     true
enable_katex:       true

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ['_pages', '_courses']

collections:
  publications:
    output: false

plugins:
    - jekyll-email-protect
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-mentions
    - jekyll-toc

jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"
