source 'https://rubygems.org'
    gem 'bibtex-ruby', '>= 5.1.0'
group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'kramdown', '>= 2.3.1'
    gem 'addressable', '>= 2.8.0'
    gem 'nokogiri', '>= 1.13.9'
    gem 'wdm', '>= 0.1.0'
    gem 'webrick', '~> 1.7'
    gem 'commonmarker', '>= 0.23.7'
    gem 'jekyll-toc'
    gem 'jekyll-sitemap'
    gem 'jemoji'
end
